---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-dev-be
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 9898
      nodePort: 32102
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: backend
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-dev-fe
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32103
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-staging-be
  namespace: staging
spec:
  type: NodePort
  ports:
    - port: 9898
      nodePort: 32104
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: backend
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-staging-fe
  namespace: staging
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32105
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: frontend
